### ISSUE TITLE
Missing README.md

### ISSUE THREAD

**Issue by abdalmoez** [Onboard-Team/SharedUnity3DCode-CI#1]

**Comment by Chalghouma** [comment]
Thank you for your feedback.
The repository is still under construction and an article is being written about it.
Should be complete within the next few days.

Will close the issue once it's updated.

**Comment by Chalghouma** [comment]
Closing the issue as the Readme has been added.
You can also take a look at this [article](https://www.linkedin.com/pulse/continuous-integration-unity3d-azure-devops-story-cherif-redissi/?trackingId=uefNWAusSo%2BMza%2BEkzP6DA%3D%3D)
